### ISSUE TITLE
defaultChecked radio buttons become incorrect if their order on the page changes

### ISSUE THREAD

**Issue by lilliank** [reactjs/React.NET#236] opened 2016-03-02 16:10 UTC
See repro here: https://jsfiddle.net/jx1covum 

First I render some forms with some defaultChecked radio buttons: 
![image](https://cloud.githubusercontent.com/assets/2389383/13466130/7b21fe4a-e04d-11e5-8b62-ee86b9b4ac4a.png)

And then insert another form into the list. I would expect the defaultSelected to stay on the radio buttons it was on originally (form B should still have option B selected, C should have C selected, etc).  Instead they seem to stay put on the page:
![image](https://cloud.githubusercontent.com/assets/2389383/13466195/c11b0702-e04d-11e5-8646-1499cc35f3ad.png)

Thank you!

**Comment by lilliank** [comment] 2016-03-02 16:31
Ah, disregard!  A colleague points out that this is fixed by setting the keys of the forms to the form name instead of their index.  Fair enough.  I had been thinking of keys as just "thing that needs to be unique" rather than "thing that needs to be unique and needs to not change between renders".

Cheers

**Comment by lilliank** [comment] 2016-03-02 17:26
In my defense, it is weird and confusing that I can add eg this to the option text:   {option===formName?'should be checked':''}   And it shows what I expect, though the actual defaultChecked is not updated.

**Comment by Daniel15** [comment] 2016-03-05 23:06
This repo is for ReactJS.NET, which integrates React with Microsoft's ASP.NET stack. It's not for general questions relating to React. Take a look at the [support page on the React site](https://facebook.github.io/react/support.html) to see how you can get support for React itself :) 

The issue is that if you go from having four questions/forms to having five, React doesn't know which question is the new one. In your example above, there's several possible things that could have happened. What actually happened is that "A2" was inserted below the first question. From our perspective, that's obvious. However, how is React supposed to know? You could have renamed "B" to "A2", "C" to "B", "D" to "C", and appended a new "D" to the end of the list, and in fact this is how React is treating it in your repro. React can't tell simply from an array of components where each component has moved. It gets more complicated if you rearrange the questions, for example if you move "D"  to the top and then append a new question to the bottom.

This is what keys aim to solve. The key is something that does not change between renders. It's used to determine if any components have moved around. Using the keys, React is able to know that "A2" was newly-inserted, and everything else has just moved down. I'd suggest using some sort of immutable identifier as the key. Database IDs make good keys. Failing that, you could use the title as the key ("A", "B", "C", "D", "A2") as long as there's no duplicates. Keys need to be unique.

You can read more here: https://facebook.github.io/react/docs/multiple-components.html#dynamic-children

Hope that helped! I'm going to close this out since the question doesn't specifically relate to ReactJS.NET.

**Closed by Daniel15** 2016-03-05 23:06 UTC
