### ISSUE TITLE
Problem to debug

### ISSUE THREAD

**Issue by snowjim** [reactjs/React.NET#87] opened 2015-02-18 18:25 UTC
Hi,

React renders at server side and if there is exceptions we get a Server Error in '/' Application page. This page do give some info about the problem but the location are not correct.

This is how the exception looks like : 

Server Error in '/' Application.

In file "~/Scripts/Grid.jsx": Parse Error: Line 22: Unexpected token . (at line 22 column 23)
Line: 52
Column:3

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: React.Exceptions.JsxException: In file "~/Scripts/Grid.jsx": Parse Error: Line 22: Unexpected token . (at line 22 column 23)
Line: 52
Column:3

Source Error: 

Line 8:  {
Line 9:      <h2>Index</h2>
Line 10:     @Html.React("GridBox", new
Line 11:     {
Line 12:         controlId = "myTestDiv1",

Source File: c:\Development\Bradspel_v2\Bradspel_v2\Views\Home\Index.cshtml    Line: 10 

Stack Trace: 

[JsxException: In file "~/Scripts/Grid.jsx": Parse Error: Line 22: Unexpected token . (at line 22 column 23)
Line: 52
Column:3]
   React.JsxTransformer.TransformJsxFileWithSourceMap(String filename, Boolean forceGenerateSourceMap, Nullable`1 useHarmony, Nullable`1 stripTypes) +535
   React.JsxTransformer.TransformJsxFile(String filename, Nullable`1 useHarmony, Nullable`1 stripTypes) +59
   React.ReactEnvironment.EnsureUserScriptsLoaded() +236
   React.ReactEnvironment.CreateComponent(String componentName, T props, String containerId) +64
   React.Web.Mvc.HtmlHelperExtensions.React(HtmlHelper htmlHelper, String componentName, T props, String htmlTag, String containerId) +136
   ASP._Page_Views_Home_Index_cshtml.<Execute>b__2() in c:\Development\Bradspel_v2\Bradspel_v2\Views\Home\Index.cshtml:10
   System.Web.WebPages.<>c__DisplayClass7.<RenderSection>b__5(TextWriter tw) +352
   System.Web.WebPages.HelperResult.WriteTo(TextWriter writer) +42
   System.Web.WebPages.WebPageExecutingBase.WriteTo(TextWriter writer, HelperResult content) +45
   System.Web.WebPages.WebPageBase.Write(HelperResult result) +53
   ASP._Page_Views_Shared__Layout_cshtml.Execute() in c:\Development\Bradspel_v2\Bradspel_v2\Views\Shared_Layout.cshtml:18
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +272
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +122
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +145
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer) +41
   System.Web.WebPages.<>c__DisplayClass3.<RenderPageCore>b__2(TextWriter writer) +335
   System.Web.WebPages.HelperResult.WriteTo(TextWriter writer) +42
   System.Web.WebPages.WebPageExecutingBase.WriteTo(TextWriter writer, HelperResult content) +45
   System.Web.WebPages.WebPageBase.Write(HelperResult result) +53
   System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body) +178
   System.Web.WebPages.WebPageBase.PopContext() +229
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +154
   System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance) +695
   System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer) +382
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +431
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) +39
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +116
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +529
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +106
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +321
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +185
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +133
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +56
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +40
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +34
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +70
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +139
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +59
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +40
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +44
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +39
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +62
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +139
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +59
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +40
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +39
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +39
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +39
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +70
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +139
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +59
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +40
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +40
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +38
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9651188
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

The code I got looks like this : 

var GridRow = React.createClass({
        render: function() {
            var row;

```
        row = this.props.cells.map(function(cell, i) {
            if(cell.Data.CellType == 1){
                if(cell.Data.URL!=null && cell.Data.URL.length>0){
                    return <td className={cell.Meta.HTMLClass} key={i}><a target={cell.Data.URLTarget} href={cell.Data.URL}>{cell.Data.Text}</a></td>       
                }
                else {
                    return <td className={cell.Meta.HTMLClass} key={i}>{cell.Data.Text}</td>
                }
            }
            else if(cell.Data.CellType == 2){
                if(cell..Data.IconUrl.length > 0){
                    return <td className={cell.Meta.HTMLClass} key={i}><img alt={cell.Data.Text} title={cell.Data.Text} src={cell.Data.IconSrc} /></td>
                }
                else{
                    return <td className={cell.Meta.HTMLClass} key={i}><a href={cell.Data.IconUrl}><img alt={cell.Data.Text} title={cell.Data.Text} src={cell.Data.IconSrc} /></a></td>
                }
            }
        }.bind(this));

        return (
            <tr>
                {row}
            </tr>
        );
    }
});
var GridHead = React.createClass({
    render: function() {
        if(this.props.data.columns){
            var cell = this.props.data.columns.Title;
            var htmlClass = this.props.data.columns.HTMLClass;
        }
        return (
            <th className={htmlClass}>{cell}</th>
        );
    }
});
var GridList = React.createClass({
    render: function() {
        if(this.props.data.Columns != null && this.props.data.Columns.length > 0){
            var header = this.props.data.Columns.map(function (columns, i) {
                return (
                    <GridHead data={columns} key={i} />
                );
            });

            if(this.props.data.Rows != null && this.props.data.Rows.length > 0){
                var row = this.props.data.Rows.map(function (row, i) {
                    return (
                        <GridRow cells={row.Cells} key={i} />
                    );
                });
            }
        }
        return (
            <table cellPadding="1" cellSpacing="1" className="defaultGrid">
                <tr>{header}</tr>
                <tbody>
                    {row}
                </tbody>
            </table>
        );
    }
});


var GridPager = React.createClass({
    handleNextClick: function(e) {
        e.preventDefault();
        this.props.onPaging(1);
    },
    handlePrevClick: function(e) {
        e.preventDefault();
        this.props.onPaging(-1);
    },
    render: function() {
        return(
            <div className='pageBCon'>
                <div className="lo">&nbsp;</div>
                <button type="button" onClick={this.handlePrevClick}>Prev</button>
                <div className="cPage">{this.props.currentPage}</div>
                <button type="button" onClick={this.handleNextClick}>Next</button>
            </div>
        );
    }
});

function GridFormatedData(columns, rows){
    this.Columns = columns;
    this.Rows = rows;
}

var GridBox = React.createClass({
    moreData : true,
    formatDataAndSetState: function(data) {
        var result = null;
        var tmpCol=[];
        var tmpRows=[];
        var tmpRow;
        var tmpCells=[];
        var tmpCellMeta;

        if(data.Columns != null && data.Columns.length > 0){

            for(i=0;i<data.Columns.length;i++){
                tmpCol.push ({
                    columns: data.Columns[i]
                    })
            }

            if(data.Rows != null && data.Rows.length > 0){
                for(i=0;i<data.Rows.length;i++)
                {
                    tmpRow = data.Rows[i];
                    tmpCells = [];
                    for(c=0;c<tmpRow.Cells.length;c++){

                        if(data.CellMeta != null && data.CellMeta.length > 0 && data.CellMeta[c] != null){
                            tmpCellMeta = data.CellMeta[c];
                        }
                        else{
                            tmpCellMeta = null;
                        }

                        tmpCells.push   ({
                            Data: tmpRow.Cells[c],
                            Meta: tmpCellMeta
                            })
                    }

                    tmpRows.push({
                        Cells: tmpCells
                    })
                }
            }

            result = new GridFormatedData(tmpCol, tmpRows)

        }
        return result;
    },
    loadLoadDataFromServer: function(modifier) {
        var tmpPage = this.props.pageNr + modifier;
        if((this.moreData || modifier < 0) && tmpPage > 0 && (this.props.maxPageNr == 0 || tmpPage <= this.props.maxPageNr)){
            var xhr = new XMLHttpRequest();
            xhr.open('get', this.props.url + '/?pageNr=' + tmpPage + '&take=' + this.props.pageTake, true);
            var intance = this;
            $('#' + this.props.controlId).find('.lo').css('visibility','visible');
            xhr.onload = function() {
              var data = JSON.parse(xhr.responseText);
              if(data!=null && data.Rows!=null && data.Rows.length > 0){
                intance.props.pageNr = tmpPage;
                intance.moreData = true;
                this.setState({ data: intance.formatDataAndSetState(data) });
              }
              else{ intance.moreData = false; }
              $('#' + this.props.controlId).find('.lo').css('visibility','hidden');
            }.bind(this);
            xhr.send();
        }
    },
    handlePaging: function(modifier) {
        this.loadLoadDataFromServer(modifier);
      },
    getInitialState: function() {
        return { data: this.formatDataAndSetState(this.props.initialData) };
    },
    render: function(){
        var gridClass = this.props.gridClass;
        return (
            <div id={this.props.controlId} className={this.props.gridClass}>
                <GridPager onPaging={this.handlePaging} currentPage={this.props.pageNr} />
                <GridList data={this.state.data} />
                <GridPager onPaging={this.handlePaging} currentPage={this.props.pageNr} />
                <br className="clear" />
            </div>

        );
    }
});
```

The patial view looks like this 

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section MainContainer
{
    <h2>Index</h2>
    @Html.React("GridBox", new
    {
        controlId = "myTestDiv1",
        initialData = Model,
        gridClass = "defaultGrid gridTest",
        url = Url.Action("gridrows"),
        pageNr = 1,
        pageTake = 25,
        maxPageNr = 0
    })

```
@Html.React("GridBox", new
{
    controlId = "myTestDiv2",
    initialData = Model,
    gridClass = "defaultGrid gridTest",
    url = Url.Action("gridrows"),
    pageNr = 1,
    pageTake = 25,
    maxPageNr = 0
})
```

}

We can see that line 22 and line 51 is not correct so how do I find exacly where it is in a more complexed code?

PS. Sorry for the format, its a real pain on this webpage

**Comment by PeteDuncanson** [comment] 2015-02-18 18:36
Hi @snowjim, the compilers telling you correctly as it understands it I believe, some JS bugs can be nasty to track down as they might be caused by errors further up. This one is a classic. When you get an error like this it at least lets you know that you have a syntax error or typo above that line somewhere. The parser works top down so it got to line 22 before it said "wait a minute" something is wrong here and its to do with full stops aka '.' "

So working back up from line 22 (I had to cut and paste into a text edit to find it) I find this typo on line 14 which might just well be the cause:

`if(cell..Data.IconUrl.length > 0){`

notice the extra "." which is what the compiler is complaining about I guess. Fix that and try again. Rinse repeat.

**Comment by snowjim** [comment] 2015-02-18 18:42
Yes, thats correct, its the problem but what I really asking if there is a easier way to find problems like this? This is more important if make a lot of changes without checking it first, it could be a nightmare. Cut out and test if the code runns is a last resort, is there no other way to get more precis info? I suspect that Im spoiled with the .NET ;)

**Comment by Daniel15** [comment] 2015-02-18 18:47
I'm going to try to see what can be done to make debugger easier

Have you tried the V8 engine (`React.JavaScriptEngine.ClearScriptV8` on Windows or `React.JavaScriptEngine.VroomJs` on Linux and Mac OS)? It tends to give better error messages than the MSIE engine.

**Comment by snowjim** [comment] 2015-02-19 19:59
I have now installed V8 engine and it do give me another expcetion explaination but it is still not any better. Look at this code : 

	
var FeedTopic = React.createClass({
	    render: function() {

	        return (
	        	<div className="topic">
	        		<div className="tUImgLnk">
		        		<a title={this.props.data.UserName} target="_blank" href={this.props.data.UserInfoUrl}>
		        			<img className="tUImg" src={this.props.data.UserPicSrc} />
		        		</a>
	        		</div>
	        		<div className="tInfo">
		        		<div className="tName">
		        			<a title={this.props.data.UserName} target="_blank" href={this.props.data.UserInfoUrl}>{this.props.data.UserName}</a>
		        		</div>
		        		<div className="tTime">
		        			<span>{this.props.data.DateCreated}</span>
		        		</div>
	        		<div>
	        	</div>
	        );
	    }
});


var FeedList = React.createClass({
	render: function() {
		if(this.props.data.TopicList != null && this.props.data.TopicList.length > 0){
				var topic = this.props.data.TopicList.map(function (topic, i) {
				 	return (
				 		<FeedTopic data={topic} key={i} />
				 	);
				});
			}
	  	return (
	  		<div>
  				{topic}
  			</div>
	  	);
	}
});



var FeedBox = React.createClass({
	getInitialState: function() {
	  		return { data: this.props.initialData };
	 },
	render: function(){
		return (
			<div id={this.props.controlId} className={this.props.gridClass}>
				<FeedList data={this.state.data} />
			</div>
		);
	}
});

This will throw the following server page 
In file "~/Scripts/Feed.jsx": Error: Parse Error: Line 32: Unexpected token : (at line 32 column 8)
   at ReactNET_transform_sourcemap (Script Document:52:9) -> throw new Error(ex.message + " (at line " + ex.lineNumber + " column " + ex.
Line: 52
Column:9

On line 32 I only find this : });

if I however remove the entire <div className="tInfo"> block it will work. I have tried to add it again and remove tName or tTime but that does not help.

Im not sure how the exception message really helps me?

**Comment by dustinsoftware** [comment] 2019-01-05 19:52
Closing issues older than a year, please re-open if you think this is still relevant.

**Closed by dustinsoftware** 2019-01-05 19:52 UTC
