### ISSUE TITLE
React.Core 2.4.0 does not support framework .NETCoreApp,Version=v1.0.

### ISSUE THREAD

**Issue by m1m1m1** [reactjs/React.NET#278] opened 2016-06-07 15:47 UTC
Hello
Did you ever have a error like this one:

> The dependency JavaScriptEngineSwitcher.Core 1.5.0 does not support framework .NETCoreApp,Version=v1.0.
The dependency JavaScriptEngineSwitcher.Msie 1.5.0 does not support framework .NETCoreApp,Version=v1.0.
The dependency JavaScriptEngineSwitcher.V8 1.5.2 does not support framework .NETCoreApp,Version=v1.0.
The dependency JSPool 0.4.1 does not support framework .NETCoreApp,Version=v1.0.
The dependency MsieJavaScriptEngine 1.7.0 does not support framework .NETCoreApp,Version=v1.0.
**The dependency React.Core 2.4.0 does not support framework .NETCoreApp,Version=v1.0.**

I just added a nuget (Install-Package React.Core) to my empty web project and it stoped compiling. 

Regards,
Marcin

**Comment by marvinvperez** [comment] 2016-06-09 13:17
I think it's still not supporting ASP.NET Core 1. It supports though ASP.NET Core (.Net Framework) RC 2.

**Comment by Daniel15** [comment] 2016-06-14 22:56
Duplicate of #275. This is expected at the moment. There's currently no JavaScript engine that runs on .NET Core. You will need to switch to using the full .NET Framework ("net451" rather than "netcoreapp1.0" in your project.json). Hopefully someone can get Clearscript running on .NET Core at some point.

**Comment by Daniel15** [comment] 2016-06-14 22:57
I remember seeing a comment where someone mentioned they got VroomJs running on .NET Core. I haven't had time to test that out myself though, but that is definitely one option :)

**Closed by Daniel15** 2016-06-14 22:56 UTC
