### ISSUE TITLE
Server Side Rendering Issue: ReferenceError: HTMLElement is not defined

### ISSUE THREAD

**Issue by johnsoncode** [reactjs/React.NET#285] opened 2016-06-21 21:39 UTC
I've been trying to get [ag-grid](https://www.ag-grid.com/) into an app that I'm working on but I quickly hit a wall when trying to run it. Here is the full error that I get.

```
ReactScriptLoadException: Error while loading "~/build/server.bundle.js": ReferenceError: HTMLElement is not defined
at Script Document [3]:61033:36 -> __metadata('design:type', HTMLElement)
at Script Document [3]:61081:4
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:60680:19
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:59690:23
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:59015:23
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:55405:22
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:55307:22
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:52905:30
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:52682:27
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:52147:21
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:50357:18
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:50205:29
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:49999:15
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:49985:54
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:35328:15
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:35315:24
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:34992:21
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:125:20
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:58:88
at Script Document [3]:59:31
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:49:19
at __webpack_require__ (Script Document [3]:20:30)
at Script Document [3]:40:18
at Script Document [3]:43:10
Line: 61033
Column: 36

React.JavaScriptEngineFactory.EnsureValidState()
React.JavaScriptEngineFactory.GetEngine()
...
```
The best that I could tell, it's coming from React.Net's factory. Thoughts?

**Comment by Daniel15** [comment] 2016-06-21 21:42
The script that you're loading is trying to use `HTMLElement`, which is part of the Browser Object Model and thus doesn't exist in any server-side JavaScript environment (it doesn't exist in Node.js either). The issue is at line 61033 column 36 of `~/build/server.bundle.js` You may need to see if the developer of ag-grid has a version that's suitable for server-side rendering.

Closing this out since it's a discussion rather than a bug with ReactJS.NET, but please feel free to comment if you have any other questions :)

**Closed by Daniel15** 2016-06-21 21:42 UTC
Labels: Discussion
