### ISSUE TITLE
Memory leak ?

### ISSUE THREAD

**Issue by ghost** [reactjs/React.NET#408] opened 2017-05-15 09:16 UTC
Hi guys.

When deploying my reactjs.net based webapp to a Microsoft IIS server using msdeploy/msbuild memory usage starts to build up and stays high - only way for me to lower the memory usage back to square one is 
by performing a application pool recycle.
Usually my the w3wp process uses ~150 mb memory but after a deployment it uses ~250-300 mb and stays like that until application pool recycle.

I've been fiddling around with settings such as SetMaxEngines, SetStartEngines, SetReuseJavascriptEngines etc. but no luck - unless disabling server side rendering (which I don't want to do)

**Tech info:**
Server OS: Microsoft Windows 2012 R2 - IIS 8
React version: 3.0.1 (uses v8 and clearscript)
Webstack: ASP.NET MVC 5.2.3

**React app. bootstrapping:**
ReactSiteConfiguration.Configuration
		        .SetAllowMsieEngine(false)
		        .SetLoadBabel(false)
		        .AddScriptWithoutTransform("~/my-files/somefile.bundle.js")
		        .AddScriptWithoutTransform("~/my-files/someotherfile.bundle.js")
                .SetMaxEngines(50)
                .SetStartEngines(20);

Any idea why this is happening and how to resolve this issue ?

Cheers

**Comment by ashkansiroos** [comment] 2017-06-27 09:44
I have similar problem. The IIS process grows very large, even more than 1GB.

**Comment by Taritsyn** [comment] 2017-06-27 11:27
@Skovanden In my opinion, problem in the following settings:

```csharp
…
.SetMaxEngines(50)
.SetStartEngines(20);
```

Try changing them to the following settings:

```csharp
…
.SetMaxEngines(5)
.SetStartEngines(3);
```

**Comment by Skovanden** [comment] 2017-06-27 11:32
@Taritsyn  Didn't help.

**Comment by cw-gawdeprasad** [comment] 2017-06-28 05:04
Even I have observed the same. Also I have noticed that I need to manually restart the AppPool every time I release something new for the site or I make Config changes. Otherwise the memory consumed by the IIS process keeps increasing.

**Comment by hengsoheak** [comment] 2017-06-28 10:18
I think for node or react native or react js we should deploy minimum 1Gb of RAm

**Comment by ashkansiroos** [comment] 2017-06-29 15:38
@Taritsyn 
Hi, I've set up a set of DebugDiag rules for checking memory leak.  To do that I've just ran 50 threads to call 20 of my pages and retry after receiving the answer for 5 minutes.
++
First I've set up engine switcher to use ChakraCore: The spead was OK, but the memory used by w3wp grown to more than 1 GB specially after I tried to recycle the Application pool but my dump shown me 

> WARNING - DebugDiag was not able to locate debug symbols for \ChakraCore.DLL, so the reported function name(s) may not be accurate.
> 
> \ChakraCore.DLL is responsible for 89.84 MBytes worth of outstanding allocations. The following are the top 2 memory consuming functions:
> 
> ChakraCore+9bf1c: 85.88 MBytes worth of outstanding allocations.
> ChakraCore+97730: 2.9 MBytes worth of outstanding allocations

**Saying after duration of 00:02:43  (2 minutes) there are 6,353 allocation(s) for ChakraCore  which takes 11.19 MBytes and after duration of 00:04:23 (1:30 minutes later) there are 15,633 allocation(s) or ChakraCore  which takes 36.49 MBytes which means that it is growing slowly**

> Top 5 functions by allocation count
> 
> ChakraCore+976f0   12,541 allocation(s)
> ChakraCore+97730  1,578 allocation(s)
> ChakraCore+9769f  682 allocation(s)
> ChakraCore+9c19d  264 allocation(s)
> ChakraCore+9bd5e  176 allocation(s)
> 
> Top 5 functions by allocation size
> ChakraCore+9bf1c  34.25 MBytes
> ChakraCore+97730  1.4 MBytes
> ChakraCore+976f0  472.19 KBytes
> ChakraCore+9769f  285.79 KBytes
> ChakraCore+a6942  30.47 KBytes
>  
> Function details
> 
> Function   ChakraCore+9bf1c 
> Source Line    
> Allocation type   Virtual memory allocation(s) 
> Allocation Count   176 allocation(s) 
> Allocation Size   34.25 MBytes 
> Leak Probability   49% 
> 
> Function   ChakraCore+97730 
> Source Line    
> Allocation type   Heap allocation(s) 
> Heap handle   0x00000000`00000000 
> Allocation Count   1578 allocation(s) 
> Allocation Size   1.4 MBytes 
> Leak Probability   62% 
> 
> Function   ChakraCore+976f0 
> Source Line    
> Allocation type   Heap allocation(s) 
> Heap handle   0x00000000`00000000 
> Allocation Count   12541 allocation(s) 
> Allocation Size   472.19 KBytes 
> Leak Probability   58% 
> 
> Function   ChakraCore+9769f 
> Source Line    
> Allocation type   Heap allocation(s) 
> Heap handle   0x00000000`00000000 
> Allocation Count   682 allocation(s) 
> Allocation Size   285.79 KBytes 
> Leak Probability   60% 
> 
> Function   ChakraCore+a6942 
> Source Line    
> Allocation type   Heap allocation(s) 
> Heap handle   0x00000000`00000000 
> Allocation Count   150 allocation(s) 
> Allocation Size   30.47 KBytes 
> Leak Probability   4% 
> 
> Function   ChakraCore!JsDisposeRuntime+1553f 
> Source Line    
> Allocation type   Heap allocation(s) 
> Heap handle   0x00000000`00000000 
> Allocation Count   54 allocation(s) 
> Allocation Size   27.7 KBytes 
> Leak Probability   98% 
> 
> 
> Function   ChakraCore+9bd5e 
> Source Line    
> Allocation type   Heap allocation(s) 
> Heap handle   0x00000000`00000000 
> Allocation Count   176 allocation(s) 
> Allocation Size   27.5 KBytes 
> Leak Probability   49% 
> 
> 
> Function   ChakraCore+9c19d 
> Source Line    
> Allocation type   Heap allocation(s) 
> Heap handle   0x00000000`00000000 
> Allocation Count   264 allocation(s) 
> Allocation Size   10.31 KBytes 
> Leak Probability   44% 
> 
> 
> Function   ChakraCore!JsDisposeRuntime+154c8 
> Source Line    
> Allocation type   Heap allocation(s) 
> Heap handle   0x00000000`00000000 
> Allocation Count   4 allocation(s) 
> Allocation Size   2 KBytes 
> Leak Probability   4% 
> 
> Function   ChakraCore+9de30 
> Source Line    
> Allocation type   Heap allocation(s) 
> Heap handle   0x00000000`00000000 
> Allocation Count   8 allocation(s) 
> Allocation Size   320 Bytes 
> Leak Probability   72%

**Comment by ashkansiroos** [comment] 2017-06-29 15:47
Then I've changed the engineswitcher to use V8. The results was very bad :( 
The site was very slow and it was drinking the memory like if it is beer :\ and there was some exceptions for some reason.

> \v8-x64.dll is responsible for 5.22 GBytes worth of outstanding allocations. The following are the top 2 memory consuming functions:
> 
> v8_x64!v8::Extension::dependencies+73fd: 5.18 GBytes worth of outstanding allocations.
> v8_x64!v8::Extension::dependencies+877e: 42.5 MBytes worth of outstanding allocations.
> This was detected in w3wp.exe__dev.berendsen.com__PID__20824__Date__06_29_2017__Time_04_46_35PM__237__Leak Dump - **Private Bytes.dmp**
> 
> \v8-x64.dll is responsible for 5.73 GBytes worth of outstanding allocations. The following are the top 2 memory consuming functions:
> 
> v8_x64!v8::Extension::dependencies+73fd: **5.68 GBytes** worth of outstanding allocations.
> v8_x64!v8::Extension::dependencies+877e: 46.75 MBytes worth of outstanding allocations.
> 
> This was detected in w3wp.exe__dev.berendsen.com__PID__20824__Date__06_29_2017__Time_04_47_20PM__267__Leak Dump - **Virtual Bytes**.dmp

> Number of allocations   103,860 allocations 
> Total outstanding handle count   1,670 handles 
> Total size of allocations   5.61 GBytes 
> clr 62,755 allocation
> webengine4 20,273 allocation(s)
> v8_x64  211 allocation(s)
> 
> v8_x64 5.22 **GBytes**
> webengine4  316.09 MBytes
> clr  79.24 MBytes
> 
> Virtual memory Globals.Manager 5.28 GBytes
> 
> 
> Module details for v8_x64
>  
> Module Name   v8_x64 
> Allocation Count   211 allocation(s) 
> Allocation Size   5.22 GBytes 
> 
> 
> v8_x64!v8::Extension::dependencies+73fd  191 allocation(s)
> v8_x64!v8::Extension::dependencies+877e  20 allocation(s) 
> 
> v8_x64!v8::Extension::dependencies+73fd  **5.18 GBytes**
> v8_x64!v8::Extension::dependencies+877e  42.5 MBytes 
> 
>  
> 
>  Function details
> 
> Function   v8_x64!v8::Extension::dependencies+73fd 
> Source Line    
> Allocation type   Virtual memory allocation(s) 
> Allocation Count   191 allocation(s) 
> Allocation Size   5.18 GBytes 
> Leak Probability   84% 
> 
> 
> 
> Call stack sample 1
> 
> Address   0x00000000`00000000 
> Allocation Time   00:30:00 since tracking started 
> Allocation Size   512 MBytes 
> 
> 
> 
> 
> Function
> 
>   Destination
> 
> LeakTrack+22a1f    
> v8_x64!v8::Extension::dependencies+73fd    
> v8_x64!v8::Extension::dependencies+312b3    
> v8_x64!v8::Extension::dependencies+31501    
> v8_x64!v8::ExternalResourceVisitor::VisitExternalString+275d4    
> v8_x64!v8::ExternalResourceVisitor::VisitExternalString+1b84    
> v8_x64!v8::Isolate::New+198    
> ClearScriptV8_64+11f2a    
> ClearScriptV8_64+114b8    
> 0x7FFAEBED41A8    
> 
> 
> 
> Call stack sample 2
> 
> Address   0x00000000`0012d000 
> Allocation Time   00:30:09 since tracking started 
> Allocation Size   1.18 MBytes 
> 
> 
> Function
> 
>   Destination
> 
> LeakTrack+22a1f    
> v8_x64!v8::Extension::dependencies+73fd    
> v8_x64!v8::Extension::dependencies+2c8d7    
> v8_x64!v8::Extension::dependencies+2cc08    
> v8_x64!v8::Extension::dependencies+2cece    
> v8_x64!v8::ExternalResourceVisitor::VisitExternalString+154ab    
> v8_x64!v8::ExternalResourceVisitor::VisitExternalString+15603    
> v8_x64!v8::Isolate::NumberOfHeapSpaces+10d50    
> v8_x64!v8::Isolate::NumberOfHeapSpaces+11f4f    
> v8_x64!v8::Isolate::NumberOfHeapSpaces+1202a    
> v8_x64!v8::FunctionTemplate::NewRemoteInstance+467    
> v8_x64!v8::String::NewFromTwoByte+138    
> ClearScriptV8_64+41c7    
> 0x7FFAEC1CBA1B    
> 
> 
> 
> Function   v8_x64!v8::Extension::dependencies+877e 
> Source Line    
> Allocation type   Virtual memory allocation(s) 
> Allocation Count   20 allocation(s) 
> Allocation Size   42.5 MBytes 
> Leak Probability   95% 
>

**Comment by Taritsyn** [comment] 2017-07-06 15:03
@ashkansiroos From your reports it is seen, that memory leaks are not present in .NET wrappers, but are present in native libraries. That is, it turns out, that cause of leaks are the original libraries (`ChakraCore.dll` and `v8-x64.dll`), which are used in a huge number of projects (including Node.js).

> Then I've changed the engineswitcher to use V8. The results was very bad :(
The site was very slow and it was drinking the memory like if it is beer :\ and there was some exceptions for some reason. V8 is using 5.68 GBytes of memory with only 200 allocations.

Back in october last year, [ClearScript.V8 showed very good results](https://asmagin.com/2016/10/22/how-to-marry-reactjs-and-sitecore-with-webpack-part-3-js-engines-performance/) in terms of memory consumption.

@ashkansiroos @Skovanden I think the problem is that for compilation of each JSX file need to execute a large amount of JS code (`react.generated.min.js` file weighs 156 KB and `babel.generated.min.js` file weighs 650 KB). The results of the compilation of JSX files must be cached on the server side (in memory). Try to use for these purposes a combination of two libraries: [Microsoft ASP.NET Web Optimization Framework](http://aspnetoptimization.codeplex.com/) and [System.Web.Optimization.React](https://www.nuget.org/packages/System.Web.Optimization.React/).

**Comment by gunnim** [comment] 2017-09-14 20:14
@Skovanden sounds similar to the issue i was having, it disappeared when i upgraded the JavascriptEngineSwitcher libraries to version 2.4.10

**Comment by dustinsoftware** [comment] 2019-01-05 17:00
Closing issues older than a year, please re-open if you think this is still relevant.

**Closed by dustinsoftware** 2019-01-05 17:00 UTC

**Comment by congaductq** [comment] 2019-02-27 09:11
I tried to run the `tutorial code` (https://github.com/reactjs/React.NET/tree/master/tutorial-code), and surprisingly I faced to the same problem with only one request sent.


Run on Windows 10 and Visual Studio 2017.

![untitled](https://user-images.githubusercontent.com/19276305/53478415-587d4700-3aa9-11e9-9d29-d3dab875b27c.png)

Any solution for the `tutorial code`?

**Comment by Taritsyn** [comment] 2019-02-27 10:57
@congaductq I get more than 800 MB only with Visual Studio.
