### ISSUE TITLE
[Question] Compatible flux library

### ISSUE THREAD

**Issue by Todilo** [reactjs/React.NET#136] opened 2015-06-04 14:38 UTC
Firstly, great work with this library. For my project it is very essential that server-rendering is enabled so I have a question regarding Flux. Is there anything you need to think about when choosing a Flux library? From browsing the web some solution does not seem to be suitable for server-side rendering.

Any thoughts regarding this? Is there anything else to think about when connecting other libraries to allow for server-side-rendering=

**Comment by Daniel15** [comment] 2015-06-05 09:18
Unfortunately I haven't spent much time trying Flux libraries with ReactJS.NET yet. It'd be mostly similar to choosing a library for other server-side JavaScript technologies such as Node.js. Notably, singletons (like in Facebook's "vanilla" Flux examples) do not work. You need to have stores that are instantiated, so every request has a different instance of the store even though you're reusing the same JavaScript engine server-side.

In theory, any  Flux library that says it's "isomorphic" should work for server-side rendering.

Let me know how you go :)

**Comment by Todilo** [comment] 2015-06-05 09:20
Ok, then I will see of all the Flux libraries I will choose :). Thank ou

**Comment by Todilo** [comment] 2015-06-12 06:48
It looks like I am ending up with fluxible http://fluxible.io/ , for both routing as well as flux (isomorphic) but well it is really difficult so set everything up! There are so many libraries out there(for flux and routing but sooooo little documentation and well trying to set it up under .net has 0 documentation).

**Comment by PeteDuncanson** [comment] 2015-06-15 13:23
I would strongly suggest you roll with Facebooks Vanilla Flux pattern (using their dispatcher https://github.com/facebook/flux) to get your head into the flux pattern first. You only need to wire up one store with actions etc. so you can see how it all works. Get this working server-side and then and only then would I switch to using one of the Flux wrappers/frameworks as they hide a lot of the "magic" from you but in doing so hide a lot of the understanding/context too. Personally it was only through using Flux "raw" that I "got it".

Additionally a lot of the flux frameworks I've seen abstract a little too much away which can make it tricky to go off the beaten path sometimes plus its yet another tech that the developer coming behind you has to learn before they can debug your stuff. I know the Facebook dispatcher is battle tested so I'd rather use that.

Getting it working server-side takes some thought to avoid any headaches. The issue is your server won't be doing any of the ajaz loading etc. So you need to disable it or change how you load it for server-side. It only need the data once, not for every update. The trick we use is to check if we are running server-side and if so when our app's ComponentWillMount to setup the store with the data it will need. This should trigger a "data as changed" update from your store which will get everything to redrawn. Its that redrawn that will be caught by React.renderToString server-side and sent down the wire.

That should help but I know its not 100% complete, I need to get an better example up which I'll work on this week.

**Comment by jslatts** [comment] 2015-06-17 02:46
We are using Reflux with Reactjs.NET and are quite happy with it. Reflux is a deviation from the official Flux pattern in that eschews the dispatcher. I prefer its simplicity over the other Flux implementations I looked at.

The only issue we had getting it to work server-side was that Reflux depends on a promise library that depends on the window object. We used Browserify to shim an empty module in place of the promise library for our server-side JS bundle (we use separate JS bundles for server vs client). Reflux is loaded on the server, but none of its methods are invoked, so this works out ok.

For the server-side render, we pass in props in the standard way and render our React components fully based on those props. None of the Reflux stores are ever populated (this means avoiding doing any AJAX calls in the initialization method of the stores). 

On the client-side, the components are bootstrapped using the embedded JSON via the standard Reactjs.NET process, but all subsequent state changes and AJAX interactions are handled via Reflux.

This is basically cheating in the sense that we are not actually using Reflux/Flux on the server-side. I see no downside to this for our purposes, but it may not be desirable to everyone. I think it should be possible to the bootstrap data directly into the Reflux store on the server, but we haven't bothered trying yet.

**Comment by Todilo** [comment] 2015-06-17 08:23
@PeteDuncanson is facebox flux even possible to have server-side. From what I have read it uses a singleton which makes it not possible to use on serverside. If it is I would of cause like to go with it because as you say, it is battletested, so the bigger the library the better.

I will watch your starterkit if you get the build fixed it would be super helpful.

**Comment by Daniel15** [comment] 2015-06-17 08:26
> that Reflux depends on a promise library that depends on the window object

Huh, that's really strange. So the promise library doesn't work in any server-side JavaScript environment? A good promise library should work both server-side and client-side.

>  From what I have read it uses a singleton which makes it not possible to use on serverside

That's what the Facebook Flux examples use, but the stores don't have to be singletons.  The only pre-built part of Facebook Flux is the dispatcher, which is a class you instantiate.

**Comment by PeteDuncanson** [comment] 2015-06-17 09:37
Boy is my list of "blog posts to write" getting long! 

Flux is doable on the server side with a little slight of hand as discussed. We use global stores in our stuff for ease. I'll get something written up asap.

Pete

**Comment by jslatts** [comment] 2015-06-17 15:30
> Huh, that's really strange. So the promise library doesn't work in any server-side JavaScript environment? A good promise library should work both server-side and client-side.

I misrembered my issue. The library in question is native-promise-only, which is a promise shim used by Reflux. When trying to render server-side with clearscript, it was invoking setTimeout which was not defined in the ClearScript api. More about this can be found here: spoike/refluxjs#250 and spoike/refluxjs#302.

> From what I have read it uses a singleton which makes it not possible to use on serverside

Reflux does not use singletons, which is one of the reason's I like it.

**Comment by dustinsoftware** [comment] 2019-01-05 19:50
Closing issues older than a year, please re-open if you think this is still relevant.

**Closed by dustinsoftware** 2019-01-05 19:50 UTC
Labels: Discussion
