### ISSUE TITLE
Require is not define: Trying to use loadable-components

### ISSUE THREAD

**Issue by felipetoffolo1** [reactjs/React.NET#731] opened 2019-02-13 16:49 UTC
Hi guys.

I'm trying to use the loadable-components library.
I'm created a render function and it was going fine.

`namespace React.RenderFunctions
{
    /// <summary>
    /// Render functions for React-JSS. https://github.com/cssinjs/react-jss
    /// Requires `react-jss` to be exposed globally as `ReactJss`
    /// </summary>
    public class LoadableComponents : RenderFunctionsBase
    {
        /// <summary>
        /// HTML style tag containing the rendered styles
        /// </summary>
        public string RenderedStyles { get; private set; }

        /// <summary>
        /// Implementation of PreRender
        /// </summary>
        /// <param name="executeJs"></param>
        public override void PreRender(Func<string, string> executeJs)
        {
            string json = File.ReadAllText(System.AppDomain.CurrentDomain.BaseDirectory + @"frontend/js/server-side-app/loadable-stats.json");
                executeJs($"var extractor = new ChunkExtractor({ json });");
        }

        /// <summary>
        /// Implementation of WrapComponent
        /// </summary>
        /// <param name="componentToRender"></param>
        /// <returns></returns>
        public override string WrapComponent(string componentToRender)
        {
            return ($"extractor.collectChunks({componentToRender})");

        }

        /// <summary>
        /// Implementation of PostRender
        /// </summary>
        /// <param name="executeJs"></param>
        public override void PostRender(Func<string, string> executeJs)
        {
            RenderedStyles = executeJs(" extractor.getStyleTags()");
        }
    }
}`

my problem is that the loadable/server library add on the code a 
`return require(modulePath)`
that the javascript engine is giving a error: Require is not defined

Just wanna ask if anyone has any idea of what i can do to solve this,

Thanks very much

**Comment by dustinsoftware** [comment] 2019-02-14 04:51
There isn’t (yet) an API that lets you load arbitrary chunks from disk, but I made a branch here that demonstrates how this could be accomplished. 

https://github.com/dustinsoftware/React.NET/tree/react-loadable

**Comment by dustinsoftware** [comment] 2019-02-23 05:39
Took another look React loadable and Loadable Components appear to be very similar in design so in _theory_ it won't take much to support this.

@felipetoffolo1 would you be willing to try out a debug build? Can you pull that branch and see if it's what you're looking for?

**Comment by felipetoffolo1** [comment] 2019-02-23 09:19
@dustinsoftware sure I can give it a try this week.
Would be great to use Loadable Components. 
I wish I could help on the code part too. But my .net experience is quite short. I'm a frontend dev. But I'm happy to help as possible.

**Comment by xtroncode** [comment] 2019-05-10 07:04
Hey @felipetoffolo1  , I stumbled upon this as I was facing the same issue. After struggling a lot I fixed it by making the following change in  PreRender Hook
`executeJs(@"var extractor = new ChunkExtractor({ stats: "+ json +@"});");`

I think the issue is the way the stats were passed to the ChunkExtractor,

**Comment by dustinsoftware** [comment] 2019-05-19 04:27
Per the loadable-components [docs](https://www.smooth-code.com/open-source/loadable-components/docs/loadable-vs-react-lazy/) it looks like there is support for Babel 7 which has been merged already in this repo.. so I am planning on updating this branch to get it working with loadable-components and then releasing it as an experimental feature.

**Comment by felipetoffolo1** [comment] 2019-06-10 13:57
> Hey @felipetoffolo1 , I stumbled upon this as I was facing the same issue. After struggling a lot I fixed it by making the following change in PreRender Hook
> `executeJs(@"var extractor = new ChunkExtractor({ stats: "+ json +@"});");`
> 
> I think the issue is the way the stats were passed to the ChunkExtractor,

Hey @xtroncode  is it working well for you? I'm thinking about giving it another go, Is the css been splitted too?

**Comment by xtroncode** [comment] 2019-06-11 09:41
@felipetoffolo1  Yes, I was able to get imported css files (inside a loadable component ) split in the output

**Comment by felipetoffolo1** [comment] 2019-06-14 08:47
> @felipetoffolo1 Yes, I was able to get imported css files (inside a loadable component ) split in the output

that is great @xtroncode for some reason I keep getting a error saying windows are not defined.
Did you had to do something for that?

**Comment by felipetoffolo1** [comment] 2019-06-19 08:42
@xtroncode can you share your webpack and babel config with me please?

**Comment by xtroncode** [comment] 2019-06-19 09:05
@felipetoffolo1 
Here's my test project
[ReactTest.zip](https://github.com/reactjs/React.NET/files/3305263/ReactTest.zip)

You have be careful with using DOM apis (eg. `window`) as they are not available on the server, here's a good explanation https://itnext.io/tips-for-server-side-rendering-with-react-e42b1b7acd57

**Comment by felipetoffolo1** [comment] 2019-06-24 15:57
@xtroncode big thanks. That helped me a lot. I had limiting the number of chunks on ssr build to 1. And use loadable-stats file generated by the client side for the extractor in the server side.

**Comment by xtroncode** [comment] 2019-06-25 05:22
@felipetoffolo1  happy to help :+1:

**Comment by johannesaxner-valtech** [comment] 2019-10-09 12:57
Is there any way to get this running with a stable release of React.NET or do I need to mess around with a fork?

**Comment by xtroncode** [comment] 2019-10-09 17:11
The attached example works with the stable release

**Comment by dustinsoftware** [comment] 2019-10-10 00:36
Just an update, I haven’t had the time to revisit this. I’d love to see a PR if someone figures out a way to get this working. Would plan to flag it behind an experimental flag as we figure out the right API.

**Comment by WesselKroos** [comment] 2020-05-04 17:46
I was able to make this work without a custom implementation of the RenderFunctionsBase class.

See my answer here for the implementation:
https://github.com/reactjs/React.NET/issues/1098#issuecomment-623597987

**Comment by dustinsoftware** [comment] 2020-08-18 04:00
At this point I'm going to close the code-splitting issues; it's likely this library will never support that use case for SSR. It's possible today for your components to use dynamic import after the main component has loaded (the webpack example does this).

**Closed by dustinsoftware** 2020-08-18 04:00 UTC
Labels: Enhancement, Help Wanted
