### ISSUE TITLE
Events not working with Server-side rendering

### ISSUE THREAD

**Issue by nyccyn** [reactjs/React.NET#209] opened 2015-12-16 12:44 UTC
I'm following the tutorial on VS2010, when I tried to change to server-side rendering it seems like the events are not rendering (onSubmit and I tried with onClick as well) .

**Comment by Jodith** [comment] 2016-01-05 13:51
Same here.
I tried to bind to onChange on an input element and it doesn't work with server-side rendering at all.
Will it be fixed or is there a workaround? Seems like a really important feature. :+1:

**Comment by CoskunSunali** [comment] 2016-01-26 21:23
Are there any updates on this one?

**Comment by AustinWinstanley** [comment] 2016-03-01 06:03
Same. onClick just doesn't render with vNext and server side rendering

**Comment by Daniel15** [comment] 2016-04-13 04:05
Do you have an example of some code that's not working properly and how you're adding the event handlers?

**Comment by ptcc** [comment] 2016-06-09 14:17
React render has to be called also on the client side to attach the events... I have not used react.Net, but it is the same with plain react with node server side rendering... it just creates the html and the render has to be called client side also (react will compare the rendering results and not re-render on the dom, effectively taking advantage of server side rendering)

**Comment by jpsingleton** [comment] 2016-12-06 12:37
I just pulled the [latest tutorial code](/reactjs/React.NET/tree/master/tutorial-code) from this repository and the server side rendering fails to bind the events. The problem is with remarkable.

If you strip out all the markdown bits then it works as expected. I think remarkable just complicates [the tutorial](/reactjs/React.NET/blob/master/site/jekyll/getting-started/tutorial.md) and should be removed to simplify it. I'm happy to do this if it's a good idea. There's some broken formatting to tidy up too.

P.S. To run the tutorial on your installed framework, e.g. ASP.NET 1.0.1 (rather than 1.0.0), simply delete the [`global.json`](/reactjs/React.NET/blob/master/tutorial-code/global.json) file.

**Comment by dustinsoftware** [comment] 2019-01-05 19:46
Closing issues older than a year, please re-open if you think this is still relevant.

**Closed by dustinsoftware** 2019-01-05 19:46 UTC
