### ISSUE TITLE
Source level debugging in Visual Studio?

### ISSUE THREAD

**Issue by kendallb** [reactjs/React.NET#658] opened 2019-01-09 03:47 UTC
Hi Guys,

I have started doing React programming using your tooling to get it working in our ASP.NET MVC application and I really like it! However today I decided to debug some of my Javascript and discovered that while Visual Studio supports debugging Javascript via Chrome nicely, it couldn't seem to figure out how to properly set breakpoints and deal with the .jsx files? I checked in Chrome and Chrome is able to see the source maps just fine so I can debug the code in the browser, but I have gotten used to debugging Javascript within Visual studio as it is convenient to use tools you are familiar with.

Anyway, am I doing something wrong and I need to set something up differently for it to support debugging the JSX files within Visual Studio, or is this simply not possible? The Bridge.NET project (C# to Javascript compiler that I wished could support JSX syntax!) can support debugging their Javascript files in Visual Studio, so it should be possible somehow?

I might check and see if this is supported in Rider as I have that also, otherwise worst case I will just debug it in Chrome.

**Comment by dustinsoftware** [comment] 2019-01-12 18:04
As of today this library does not support debugging the original JSX files from Visual Studio. Since the files are first compiled with Babel (either at runtime or with webpack), the debugger needs source maps to know where the current execution context maps to in the original source.

If someone is up for implementing this I'd be happy to discuss some approaches. For now I'll close the issue until someone wants to take this on.

cc #655

**Comment by dustinsoftware** [comment] 2019-01-16 14:45
I'll keep this issue open if you'd like to work on it :) I haven't investigated what Visual Studio needs, but a helpful starting point would be to look at the source maps support [in Babel](https://babeljs.io/docs/en/options#source-map-options) and exporting that, since that's what we'll need to capture. It may make sense to keep source maps around in a cache as scripts are compiled at runtime.

**Comment by dustinsoftware** [comment] 2019-01-16 14:48
Hah. Just as I typed that I realized that this library [already has basic support](https://github.com/reactjs/React.NET/blob/b8521d954c5ad7c6c943c65234aa7cf93f13455a/src/React.Web/BabelHandler.cs#L68) for generating and passing source maps via a HTTP header. I'm not sure what additional data Visual Studio needs beyond that if it's already hooked into Chrome's debugger...

**Comment by kendallb** [comment] 2019-01-18 15:48
Yeah I will take a look.

**Comment by kendallb** [comment] 2019-01-19 18:51
Ok from what I can work out, generally the source maps live in a .map file next to the regular files (when build with a build tool like webpack), but they are referenced with a special comment at the end of the generated file like so:

//@ sourceMappingURL=app.js.map

So I suspect maybe all we need to do is add that line to the end of the compiled .jsx file that is served up, which has a reference to the same .jsx file with the source map query string parameter added? 

I am not quite sure where to start looking at how to add that to the generated file, perhaps you can give me some pointers?

http://blogs.microsoft.co.il/gilf/2013/01/12/quick-tip-enabling-typescript-debugging/

**Comment by dustinsoftware** [comment] 2019-01-28 15:09
Take a look in [Babel.cs](https://github.com/reactjs/React.NET/blob/master/src/React.Core/Babel.cs#L175), it should be pretty straight forward.

I can take a look at this again in a couple weeks, I'm going to be pretty busy at home and will be taking a slight break from OSS work :)

**Comment by kendallb** [comment] 2019-01-28 15:41
I have run out of time myself for this. I am actually planning to transition to Typescript with webpack and Bridge.net.

**Comment by kendallb** [comment] 2019-01-28 20:23
Yes, I think so. It generates Javascript by compiling C# just like Typescript, so it should be able to support server side rendering the same as using Typescript or native Javascript. The one thing it lacks is declarative markup like JSX or TSX, so I am trying to figure out if there is a way I can use JSX or TSX files for my layout, and C# for all the logic :)

**Comment by dustinsoftware** [comment] 2019-05-27 05:15
This is getting stale and I don't have plans to visit this issue in the near future, so closing this out. For whoever finds this in the future I will happily accept a PR if someone finds the root cause here.

**Closed by dustinsoftware** 2019-05-27 05:15 UTC
Labels: Discussion, Enhancement
