### ISSUE TITLE
Error on startup in core 2.0 'React.AspNet.HttpContextLifetimeProvider`

### ISSUE THREAD

**Issue by dasjestyr** [reactjs/React.NET#433] opened 2017-08-13 21:21 UTC
After having followed the first part of the tutorial, I try to run the web site and it throws on startup with 

> "Cannot resolve scoped service 'React.AspNet.HttpContextLifetimeProvider+PerRequestRegistrations' from root provider."

Is this just the result of a breaking change by AspNetCore 2.0? Is there an incoming fix?

**Comment by Daniel15** [comment] 2017-08-13 21:22
Likely a breaking change in 2.0. I haven't tested with 2.0 yet. Feel free to submit a pull request if you do work out what broke.

**Comment by dasjestyr** [comment] 2017-08-13 22:05
I'd give it a crack but I can't seem to get it to build. dev-build.bat is completing with errors. "**/*.resx couldn't be found" is about the only intelligible output I'm seeing at the moment.

**Comment by Daniel15** [comment] 2017-08-13 22:07
Does it look like this?
```
Microsoft.Common.CurrentVersion.targets(2867,5): error MSB3552: Resource file "**/*.resx" cannot be found.
```

You may be hitting this issue: https://dan.cx/2017/05/fixing-msb3552-resource-file-resx-cannot-be-found:

> this is caused by a long-standing MSBuild bug: [Wildcard expansion is silently disabled when a wildcard includes a file over MAX_PATH](https://github.com/Microsoft/msbuild/issues/406). [...] In my case, my build server was running an old version of npm, which is known to create extremely long file paths. The way to "fix" this is by reducing the nesting of your folders. If you're using npm, upgrading to a newer version (or switching to Yarn) should fix the issue. Otherwise, you may need to move your project to a different directory, such as a directory in the root of C:\.

**Comment by dasjestyr** [comment] 2017-08-13 22:38
That's the one

**Comment by Daniel15** [comment] 2017-08-13 22:50
One of the causes I've seen of that is old npm versions. Check `npm --version` and if it's 2.x or older then `npm install --global npm` to upgrade.

**Comment by dasjestyr** [comment] 2017-08-13 23:21
Yeah I saw that in the instructions but that didn't seem to help. Then I tried moving the repo folder all the way down to my C: drive to help shorten the paths, but windows is warning me that the filenames are still too long.

**Comment by ShikiGami** [comment] 2017-08-27 10:02
I got it to run without any modification to the React.Net source. The problem is the way now things are initialized in Startup.cs in ASP.NET Core 2.0

The problem is that now services are not available at some points in the Startup process. To ensure that 'React.AspNet.HttpContextLifetimeProvider+PerRequestRegistrations' is available the easiest way is to change the type of `ConfigureServices(IServiceCollection services)` from `void` to `IServiceProvider` and add the following line at the end of `ConfigureServices(IServiceCollection services)` :
`return services.BuildServiceProvider();`

Either way I'm going to make a pull request where I update the whole React.NET to ASP.NET Core 2.0. One of the biggest advantages is that now with .NET Standard 2.0 is no longer necessary to make so many divisions between .NET Framework and .NET Core libraries.
The only inconvenience is that support would go from .NET Framework 4.5.1 to 4.6.1.

**Comment by amccool** [comment] 2017-08-27 18:29
@ShikiGami your fix works for me

change 
`        public void ConfigureServices(IServiceCollection services)`
to
`        public IServiceProvider ConfigureServices(IServiceCollection services)`

and `return services.BuildServiceProvider();`

**Comment by dasjestyr** [comment] 2017-08-27 21:16
It may be worth noting that for obvious reasons, only had the problem on a windows machine. I had no issue starting a new project on Linux.

**Comment by maksgit** [comment] 2017-09-04 08:13
@ShikiGami 
I looked at your repo [https://github.com/ShikiGami/React.NET/blob/origin/core20update/tutorial-code/Startup.cs](url) and didn't see changes which you mentioned. Maybe I do something wrong?

**Comment by oleh-zheleznyak** [comment] 2017-09-27 20:12
@ShikiGami, 
your fix works like a charm! Many thanks!

**Comment by Daniel15** [comment] 2017-10-11 11:15
Hey @ShikiGami, thanks for your comment! I actually hit this same error when updating my own website, and your comment helped resolve it :)

Please feel free to open a pull request updating the documentation on the ReactJS.NET website. The documentaton page is at https://reactjs.net/getting-started/aspnetcore.html, and the contents are located in this repository. Otherwise, I'll do it, but it likely won't be for another week or two as I'm pretty busy over the next week.

**Comment by ZakariaAhmed** [comment] 2017-10-25 14:29
Thanks for the fix, works great now !

**Comment by DanielAdolfsson** [comment] 2017-12-06 08:53
Just to add some clarity as to what is happening here. 

The DependencyInjection framework is by default configured to use call-site validation whenever a service is requested. When UseReact is called, it's ensuring that the required per-request services are available by using GetService from the root call-site, and this is obviously incompatible with the call-site validation feature.

You can disable call-site validation by, in you WebHost configuration, add a simple:
`.UseDefaultServiceProvider(options => options.ValidateScopes = false)`

**Comment by dustinsoftware** [comment] 2018-01-06 22:57
The samples have been updated to .NET Core 2.0, so closing this issue for now. Please feel free to re-open if you'd like some more help!

**Closed by dustinsoftware** 2018-01-06 22:57 UTC

**Comment by ngohungphuc** [comment] 2018-01-29 08:25
The issue still happened in .Net Core 2.0

**Comment by dustinsoftware** [comment] 2018-01-29 15:21
Hi there, what version of React.AspNet are you building against? The samples in this repo use .Net Core 2.0 so I’m curious why you are still getting errors.

**Comment by ngohungphuc** [comment] 2018-01-29 15:58
I'm using lastest version of .Net core 2.0

**Comment by pinty** [comment] 2018-04-10 14:57
@ShikiGami
Thanks for pointing out the solution, t worked well!

**Comment by Masuzu** [comment] 2018-05-26 19:30
@ShikiGami Thanks for the solution!

**Comment by hermanho** [comment] 2018-09-13 01:35
The service should be checked within a scope because the class HttpContextLifetimeProvider.PerRequestRegistrations is registered as scoped lifetime.
https://github.com/reactjs/React.NET/blob/b048ccbc20873488ca5923282ef23978ffb4aae2/src/React.AspNet.Middleware/ReactServiceCollectionExtensions.cs#L26

Here is the code to check the service in a scope.
```csharp
private static void EnsureServicesRegistered(IApplicationBuilder app)
{
  using (var scope = app.ApplicationServices.CreateScope())
  {
    var registrations = scope.ServiceProvider.GetService<HttpContextLifetimeProvider.PerRequestRegistrations>();
    if (registrations == null)
    {
      throw new ReactNotInitialisedException("Please call services.AddReact() before app.UseReact().");
    }
  }
}
```

**Comment by jbrinkle** [comment] 2018-09-29 23:40
Happening on VS2017 new AspNetCore MVC app with Core 2.1.
However, following [migratory steps from Core 2.0 to 2.1](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1#update-the-project-file-to-use-21-versions), it seems fine. I cannot for the life of me figure out why

**Comment by hlalit03** [comment] 2018-11-15 18:37
I am trying the sample code under ReactJS.NET tutorial(https://reactjs.net/tutorials/aspnetcore.html) & despite making the changes you mentioned it doesn't work. Same works with ASP.NET Core 2.0

**Comment by dustinsoftware** [comment] 2018-11-15 19:49
I published a beta that fixes this error, please update to the latest beta
and try again.

**Comment by milesvdw** [comment] 2018-12-12 20:52
> @ShikiGami your fix works for me
> 
> change
> ` public void ConfigureServices(IServiceCollection services)`
> to
> ` public IServiceProvider ConfigureServices(IServiceCollection services)`
> 
> and `return services.BuildServiceProvider();`

This worked perfectly. Thanks so much! Saved me a real headache.

**Comment by mbileya** [comment] 2019-06-15 17:43
@ShikiGami - your fix worked for me too. Thanks!
