### ISSUE TITLE
JSX not transpiling on the fly on ASP.NET Core (.NET Framework) RC2

### ISSUE THREAD

**Issue by marvinvperez** [reactjs/React.NET#279] opened 2016-06-09 13:32 UTC
Hi,
The tutorial works specifically to ASP.NET MVC 4 & 5. But I'm trying to use ReactJS.NET to ASP.NET Core (.NET Framework) RC 2. **Note: I did use .NET Framework NOT .NET Core.**

I am using VS 2015 Update 2 with ASP.NET Core 1 RC2. I add React.ASPNET from nugget and successfully installed.

**Startup.cs**
```
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using React.AspNet;

namespace ReactJSDotNet
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit http://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddReact();

            services.AddMvc();

            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app)
        {
            // Initialise ReactJS.NET. Must be before static files.
            app.UseReact(config =>
            {
                config.SetAllowMsieEngine(false);
                // If you want to use server-side rendering of React components,
                // add all the necessary JavaScript files here. This includes
                // your components as well as all of their dependencies.
                // See http://reactjs.net/ for more information. Example:
                //config
                //    .AddScript("~/Scripts/First.jsx")
                //    .AddScript("~/Scripts/Second.jsx");

                // If you use an external build too (for example, Babel, Webpack,
                // Browserify or Gulp), you can improve performance by disabling
                // ReactJS.NET's version of Babel and loading the pre-transpiled
                // scripts. Example:
                //config
                //    .SetLoadBabel(false)
                //    .AddScriptWithoutTransform("~/Scripts/bundle.server.js");
            });

            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
}
```
Add Tutorial.jsx under www/scripts folder
```
var CommentBox = React.createClass({
    render: function() {
        return (
          <div className="commentBox">
            Hello, world! I am a CommentBox.
          </div>
      );
    }
});
ReactDOM.render(
  <CommentBox />,
  document.getElementById('content')
)
```
Modify index.cshtml 
```
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <title>Hello React</title>
</head>
<body>
    <div id="content"></div>
    <script src="https://fb.me/react-15.0.1.js"></script>
    <script src="https://fb.me/react-dom-15.0.1.js"></script>
    <script src="~/scripts/Tutorial.jsx"></script>  
</body>
</html>
```
Successfully build and run but getting this error in chrome
**http://localhost:9450/Scripts/Tutorial.jsx Failed to load resource: the server responded with a status of 500 (Internal Server Error)**

I think its not transpiling JSX on the fly.

Did I missed something on the setting?

Thanks

**Comment by vikranthc** [comment] 2016-07-31 19:09
I too can reproduce this.

**Comment by Daniel15** [comment] 2016-08-01 05:42
Can you please try hitting `http://localhost:9450/Scripts/Tutorial.jsx ` in your browser and see what the 500 error is?

**Comment by vikranthc** [comment] 2016-08-02 19:55
I get he following exception in the browser
```
An unhandled exception occurred while processing the request.

DirectoryNotFoundException: Failed to load the ClearScriptV8 assembly, because the directory 'C:\Users\vceakala\Documents\Visual Studio 2015\Projects\ReactApp\src\ReactApp\bin\Debug\net451\win7-x64\ClearScript.V8' does not exist.
ConstructType

JsEngineLoadException: During loading of V8 JavaScript engine error has occurred.	
See more details:

Failed to load the ClearScriptV8 assembly, because the directory 'C:\Users\vceakala\Documents\Visual Studio 2015\Projects\ReactApp\src\ReactApp\bin\Debug\net451\win7-x64\ClearScript.V8' does not exist.
ConstructType

TargetInvocationException: Exception has been thrown by the target of an invocation.
ConstructType

ClearScriptV8InitialisationException: Failed to initialise ClearScript V8. This is most likely caused by the native libraries (ClearScriptV8-64.dll and v8-x64.dll) missing from your app's Bin directory, or the Visual C++ runtime not being installed. Please ensure your app is referencing the JavaScriptEngineSwitcher.V8 NuGet package, and refer to the ReactJS.NET site for moredebugging tips.

More details: Exception has been thrown by the target of an invocation.
ConstructType

TinyIoCResolutionException: Unable to resolve type: React.JavaScriptEngineFactory
ConstructType

TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment
ConstructType

**Comment by Daniel15** [comment] 2016-10-10 02:49
Issues around loading `ClearScript.V8` should be fixed with ReactJS.NET 3.0, please upgrade and let me know if you still encounter issues 😄

**Closed by Daniel15** 2016-10-10 02:49 UTC

**Comment by manalgoyal** [comment] 2019-03-11 11:55
I am still facing the same error, Using React.AspNet v 4.0.0

**Comment by dustinsoftware** [comment] 2019-03-11 12:32
Please open a new issue and follow the directions there so we can triage. I’m your case a screenshot would also be helpful in addition to all the version numbers.
